I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script
    "So you are determined..."
Exception: Unknown keyword arguments: image

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script
    "So you are determined..."
  File "D:\renpy-6.17.7-sdk\renpy\ast.py", line 558, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "D:\renpy-6.17.7-sdk\renpy\exports.py", line 925, in say
    who(what, interact=interact)
  File "D:\renpy-6.17.7-sdk\renpy\character.py", line 817, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "D:\renpy-6.17.7-sdk\renpy\character.py", line 683, in do_display
    **display_args)
  File "D:\renpy-6.17.7-sdk\renpy\character.py", line 462, in display_say
    what_text = show_function(who, what_string)
  File "D:\renpy-6.17.7-sdk\renpy\character.py", line 667, in do_show
    **self.show_args)
  File "D:\renpy-6.17.7-sdk\renpy\character.py", line 272, in show_display_say
    return renpy.display.screen.get_widget(screen, "what", layer)
  File "D:\renpy-6.17.7-sdk\renpy\display\screen.py", line 646, in get_widget
    screen.update()
  File "D:\renpy-6.17.7-sdk\renpy\display\screen.py", line 288, in update
    self.screen.function(**self.scope)
  File "D:\renpy-6.17.7-sdk\renpy\screenlang.py", line 1236, in __call__
    values = renpy.ast.apply_arguments(self.parameters, args, kwargs)
  File "D:\renpy-6.17.7-sdk\renpy\ast.py", line 142, in apply_arguments
    return parameters.apply(args, kwargs)
  File "D:\renpy-6.17.7-sdk\renpy\ast.py", line 130, in apply
    raise Exception("Unknown keyword arguments: %s" % ( ", ".join(values.keys())))
Exception: Unknown keyword arguments: image

Windows-7-6.1.7601-SP1
Ren'Py 6.17.7.521
cryo_jelly_00 0.0
